apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laravel
    role: rolling-update
  name: laravel
  namespace: laravel
spec:
  replicas: 4
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - image: pyaephyohein/laravel
        imagePullPolicy: Always
        name: laravel