apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  labels:
    run: laravel-service
  namespace: laravel
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: laravel