apiVersion: v1
kind: Service
metadata:
  name: laravel-service
  namespace: laravel
  labels:
    tier: backend
spec:
  selector:
    app: laravel
    tier: backend
  ports:
  - protocol: TCP
    port: 80
  externalIPs:
  - 127.0.0.1